### ISSUE TITLE
作る

### ISSUE THREAD

**Issue by sh4869** [power-halation/power-halation.github.io#1]
作る

**Comment by makenowjust** [comment]
今作ってるので許してください

**Comment by makenowjust** [comment]
@sh4869 Twitterカードの設定とかfaviconとか頼む‥

**Comment by sh4869** [comment]
Twitterカードに設定するアカウントはどうする?

**Comment by makenowjust** [comment]
あー。アカウント作るほどでもないよな。ボクにしちゃってもいいけど。

設定しないとダメなんだっけ？

**Comment by sh4869** [comment]
だめみたい．ただ，analyticsで使うのがメインっぽいからそこまで気にしなくてもいい気もする

**Comment by sh4869** [comment]
https://dev.twitter.com/cards/types/summary.html
参考

**Comment by makenowjust** [comment]
了解です。ボクで設定しちゃって

**Comment by makenowjust** [comment]
Facebook対応はしなくていいです。

あと、`master`ブランチがサイトとして公開されること完全に忘れて`gh-pages`にpushしていたので、`master`に直しておいたのでpushするときに注意してください

**Comment by sh4869** [comment]
了解です

**Comment by makenowjust** [comment]
なんかダメっぽいぞ

**Comment by makenowjust** [comment]
多分descriptionが無いからだと思う

**Comment by sh4869** [comment]
あーごめん，ミスった

**Comment by sh4869** [comment]
説明は「Power Halation公式サイト」とかでいいですか?

**Comment by makenowjust** [comment]
いいんじゃないでしょうか

**Comment by makenowjust** [comment]
表示を確認した

![2016-12-28 0 43 42](https://cloud.githubusercontent.com/assets/6679325/21502920/baf058ec-cc96-11e6-97f8-d2dfd73d7109.png)

**Comment by sh4869** [comment]
:crab:

**Comment by makenowjust** [comment]
ここはSlackじゃないんだよなぁ

**Comment by makenowjust** [comment]
@sh4869 @zyouyowa ツイートボタンとか付けますか？

**Comment by sh4869** [comment]
つけてもいいんだけどあんまり効果なさそう

**Comment by makenowjust** [comment]
それもそうだ。

あとフォントの設定してないからWindowsで見たときヤバいかも

**Comment by sh4869** [comment]
Chromeだとこんな感じ
![2016-12-28 23 31 16](https://cloud.githubusercontent.com/assets/6129588/21523974/f3d26afa-cd55-11e6-90ea-fbf1145f3a29.png)

**Comment by sh4869** [comment]
IEだとそもそも最初の画面から移動しなかった～完～

**Comment by makenowjust** [comment]
しんどいなぁ
